# pubspec.yaml
name: gemini_multimodal_live_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^3.0.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  flutter_webrtc: ^0.12.5+hotfix.2
  json_annotation: ^4.9.0
  camera: ^0.11.0+2
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf # Replace with your font file path